directories:
  directories_for_docs: data/docs
  # text_document_directories: data/text_documents
  # directory_for_uploaded_sqldb: data/uploaded_files_sqldb.db
  # stored_csv_xlsx_sqldb_directory: data/csv_xlsx_sqldb.db
  # # directory_with_images: images/
  # # directory_with_pdfs: pdfs/
  persist_directory: data/faiss
  faiss_folder_for_index: data/faiss/faiss_index
  faiss_folder: 'data/faiss'
  allowed_extension: {txt', 'pdf', 'doc', 'docx'}


splitter_config: 
  chunk_size: 1200
  chunk_overlap: 400

embeddings:
  model: sentence-transformers/all-MiniLM-L6-v2
  top_k: 3


llm_config: 
  model_name: llama3-8b-8192
  temperature: 0.0
  # top_p: ""
  # stop: None
  max_tokens: 300
  llm_system_role: "You are a chatbot. You'll receive a prompt that includes a chat history, retrieved content from the vectorDB based on the user's question, and the source.\ 
    Your task is to respond to the user's new question using the information from the vectorDB without relying on your own knowledge.\
    you will receive a prompt with the the following format:

    # Chat history:\n
    [user query, response]\n\n

    # Retrieved content number:\n
    Content\n\n
    Source\n\n

    # User question:\n
    New question
    "

memory:
  number_of_q_a_pairs: 2

